import os
import pandas as pd



def load_df(df: pd.DataFrame, load_path: str, file_name: str) -> str: # Se eu definir o tipo de cada arg, posso ref so na main
 
    """
    Function to transform a list of dataframes into a unique dataframe.
        
    args: df_list (Dataframe): list of dataframes generated by the extract_data function.

    return: Dataframe.

    """

    if not os.path.exists(load_path):
        os.mkdir(load_path)
    df = df.to_csv(f'{load_path}/{file_name}.csv', index=False)
    return 'File generated with success!'