import pandas as pd
from typing import List


def concat_data_frames(df_list : list) -> pd.DataFrame:
 
    """
    Function to transform a list of dataframes into a unique dataframe.
        
    args: df_list (Dataframe): list of dataframes generated by the extract_data function.

    return: Dataframe.

    """

    return pd.concat(df_list, ignore_index=True)